-- Database Schema for Sales Management System (Supabase/PostgreSQL)

-- 1. Brands Table
CREATE TABLE IF NOT EXISTS brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Stores Table
CREATE TABLE IF NOT EXISTS stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    region TEXT,
    manager_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode TEXT UNIQUE,
    name TEXT NOT NULL,
    category TEXT,
    brand_id BIGINT REFERENCES brands(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Sales Table
CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_date DATE NOT NULL,
    store_id BIGINT REFERENCES stores(id),
    product_id BIGINT REFERENCES products(id),
    quantity INTEGER DEFAULT 0,
    amount NUMERIC DEFAULT 0,
    customer_count INTEGER DEFAULT 0,
    inventory INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Brand Groups Table
CREATE TABLE IF NOT EXISTS brand_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Brand Group Members Table
CREATE TABLE IF NOT EXISTS brand_group_members (
    group_id BIGINT REFERENCES brand_groups(id) ON DELETE CASCADE,
    brand_id BIGINT REFERENCES brands(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, brand_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_sales_date ON sales(sale_date);
CREATE INDEX IF NOT EXISTS idx_sales_store ON sales(store_id);
CREATE INDEX IF NOT EXISTS idx_sales_product ON sales(product_id);
CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand_id);
